context:
  version: "0.7.1"

package:
  name: topiary
  version: ${{ version }}

source:
  url: https://github.com/tweag/topiary/archive/v${{ version }}.tar.gz
  sha256: 3d7495caf3c0ae234bd6def6f33193e026564f7818d5909641be119de811f18e

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - topiary --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Topiary is a tool in the Tree-sitter ecosystem, designed for formatter authors and formatter users.
  homepage: https://github.com/tweag/topiary
  repository: https://github.com/tweag/topiary

extra:
  recipe-maintainers:
    - danielnachun
