context:
  version: "0.6.1"

package:
  name: topiary
  version: ${{ version }}

source:
  url: https://github.com/tweag/topiary/archive/v${{ version }}.tar.gz
  sha256: e2bbac9cb46a3743cc41ca55245026580308722242c9df84bc0ef3cbb989aa81

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - topiary --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Topiary is a tool in the Tree-sitter ecosystem, designed for formatter authors and formatter users.
  homepage: https://github.com/tweag/topiary
  repository: https://github.com/tweag/topiary

extra:
  recipe-maintainers:
    - danielnachun
